export {
  Cancel01Icon,
  CheckmarkCircle02Icon,
  Tick02Icon,
  CallIcon,
  Camera01Icon,
  Copy01Icon,
  Download01Icon,
  Flag01Icon,
  Location01Icon,
  Navigation01Icon,
  LockIcon,
  Share01Icon,
  ViewIcon,
  ViewOffSlashIcon,
  Chat01Icon,
  InformationCircleIcon,
  Delete02Icon,
  Link01Icon,
  Mail01Icon,
  Settings01Icon,
  FootballIcon,
  AlertCircleIcon,
} from '@hugeicons/core-free-icons'
